### PR TITLE
Add health check endpoint ID:872

### PR DESCRIPTION
**Pull request by cracell**
https://westernmilling.tpondemand.com/entity/872

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
LGTM 👍 

Did you try against production, and if so what was the performance of the `Customer.count` method like?

**Comment by cracell** [comment]
I did. First time it took a second or two, then it felt like less than 500ms. Not sure why it was slower the first time.

**Comment by josephbridgwaterrowe** [comment]
OK, cool. We probably can't expect to hope for quicker than that 😉

**Comment by cracell** [comment]
Haha yeah....if it was Postgres/MySQL/something modern I'd be concerned but seems good for Relativity :)

**Pull request merged**
