### PR TITLE
Update Plissken Gem.

### LINKED ISSUE #35: Hash.to_snake_keys does not strip spaces.
Update gem to accommodate.

### PR DESCRIPTION
**Pull request by michaelachrisco**
Fixes #35

### CODE REVIEW

**Comment by michaelachrisco** [comment]
@josephbridgwaterrowe Please review and merge. Will do a deploy right after.

**Comment by josephbridgwaterrowe** [comment]
Are you going to leave the Gemfile pointing to your branch of plissken fork?

You could of monkey patched or used a refinement to override the default behaviour... or maybe even extended to support value processor classes?

**Comment by michaelachrisco** [comment]
If I were to monkey patch, then I would have to test that behavior in this project rather than the easy tests that the gem already provides. The change was a one liner to begin with. Honestly, I just went with the simplest solution. I plan on pointing back to the official gem once the pull request is put in.

**Comment by josephbridgwaterrowe** [comment]
Ok, cool.

**Pull request merged**
