### PR TITLE
Doorkeeper Token Reset

### LINKED ISSUE #37: Doorkeeper token expires
I got a 401 Unauthorized:
```Failure/Error: LoadRelevantCommissions.call(:batch => driver_commission_batch,
     Blanket::Unauthorized:
       401 Unauthorized
     # /Users/michaelchrisco/.rvm/gems/ruby-2.1.5@western-milling-payroll-app/gems/blanket_wrapper-2.0.1/lib/blanket/wrapper.rb:82:in `request'```

In the response: 
```
      Www-Authenticate:
      - Bearer realm="Doorkeeper", error="invalid_token", error_description="The access
        token expired"
```

### PR DESCRIPTION
**Pull request by michaelachrisco**
Fixes #37

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
Is there a reason you're disable the timeout rather than refreshing the token?

**Comment by michaelachrisco** [comment]
I am enabling the refreshing of the token using 
```use_refresh_token```.

**Comment by michaelachrisco** [comment]
We could even go so far as to refresh the token if token has expired on the gman-client side.

**Comment by josephbridgwaterrowe** [comment]
I don't see anything in your previous comment code block.

I would suggest adding a refresh to the client.

**Comment by michaelachrisco** [comment]
I uncommented the line config/initializers/doorkeeper.rb:38

I will add the refresh into the client.

**Comment by michaelachrisco** [comment]
As per our conversation, I removed the doorkeeper refresh. https://github.com/bshaffer/oauth2-server-php/issues/11

**Comment by josephbridgwaterrowe** [comment]
Are we good to merge then?

**Comment by michaelachrisco** [comment]
Yes.

**Pull request merged**
